# Generated by Django 3.2.25 on 2024-08-11 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    operations = [
        migrations.CreateModel(
            name='AudioFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Unknown Title', help_text='Song Title', max_length=255)),
                ('artist', models.CharField(default='Unknown Artist', help_text='Song Artist', max_length=255)),
                ('album', models.CharField(default='Unknown Album', help_text='Song Album', max_length=255)),
                ('genre', models.CharField(blank=True, choices=[('q', 'Unknown Genre'), ('a', 'Hip-Hop'), ('b', 'Rock'), ('c', 'Pop'), ('d', 'Jazz'), ('e', 'Classical'), ('f', 'Electronic'), ('g', 'Country'), ('h', 'Reggae'), ('i', 'Blues'), ('j', 'R&B/Soul'), ('k', 'Metal'), ('l', 'Folk'), ('m', 'Rock'), ('n', 'Punk'), ('o', 'Funk'), ('p', 'Disco'), ('r', 'Gospel'), ('s', 'Ska'), ('t', 'Latin'), ('u', 'Alternative'), ('v', 'K-Pop')], default='q', help_text='Song Genre', max_length=1)),
                ('year', models.CharField(default='2000', help_text='Song Year', max_length=4)),
                ('track_number', models.CharField(default='Unknown Track Number', help_text='Song Track Number', max_length=255)),
                ('comment', models.CharField(default='No Comment', help_text='Song Comment', max_length=255)),
                ('composer', models.CharField(default='Unknown Composer', help_text='Song Composer', max_length=255)),
                ('lyrics', models.CharField(default='No Lyrics', help_text='Song Lyrics', max_length=4320)),
                ('album_artist', models.CharField(default='Unknown Album Artist', help_text='Song Album Artist', max_length=255)),
                ('disc_number', models.CharField(default='Unknown Disc Number', help_text='Song Disc Number', max_length=255)),
                ('publisher', models.CharField(default='Unknown Publisher', help_text='Song Publisher', max_length=255)),
                ('original_artist', models.CharField(default='Unknown Original Artist', help_text='Song Original Artist', max_length=255)),
                ('encoded_by', models.CharField(default='Unknown Encoder', help_text='Song Encoder', max_length=255)),
                ('bpm', models.CharField(default='Unknown BPM', help_text='Song BPM', max_length=40)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact@email.com', max_length=254)),
                ('album_art', models.ImageField(blank=True, help_text='albumcover.jpg', max_length=60, null=True, upload_to='media/')),
                ('audio_file', models.FileField(blank=True, help_text='TrackName.mp3', max_length=180, null=True, upload_to='music/')),
                ('rms_list', models.CharField(default='Unknown RMS', help_text='Song RMS', max_length=1200000)),
                ('rms_bass', models.CharField(default='Unknown Bass RMS', help_text='Song Bass', max_length=1200000)),
                ('rms_mid', models.CharField(default='Unknown Mids RMS', help_text='Song Mids', max_length=1200000)),
                ('rms_treble', models.CharField(default='Unknown Treb', help_text='Song Treb', max_length=1200000)),
                ('discript', models.CharField(default='Unknown User Discription', help_text='Song User Discription', max_length=1200)),
                ('up_date', models.DateTimeField(verbose_name='date published')),
                ('heard', models.BigIntegerField(default=1)),
                ('likes', models.BigIntegerField(default=1)),
                ('nots', models.BigIntegerField(default=1)),
                ('dls', models.BigIntegerField(default=1)),
                ('group_album', models.ForeignKey(help_text='Album', null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.album')),
                ('munk', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audiofile', related_query_name='audiofile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['album'],
            },
        ),
    ]
