# Generated by Django 3.2.25 on 2024-08-14 05:33

from django.db import migrations, models
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='album_art',
            field=models.ImageField(blank=True, help_text='albumcover.jpg', max_length=60, null=True, upload_to=music.models.upload_to_artist_folder),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='audio_file',
            field=models.FileField(blank=True, help_text='TrackName.mp3', max_length=180, null=True, upload_to=music.models.upload_to_artist_folder2),
        ),
    ]
