# Generated by Django 3.2.25 on 2025-01-03 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20240813_2233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='audiofile',
            options={},
        ),
        migrations.AddField(
            model_name='audiofile',
            name='album2',
            field=models.CharField(default='Unknown Album', help_text='Song Album', max_length=255),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='analyzed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='artist2',
            field=models.CharField(default='Unknown Artist', help_text='Song Artist', max_length=255),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='bpm2',
            field=models.CharField(default='Unknown BPM', help_text='Song BPM', max_length=40),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='duration',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='genre2',
            field=models.CharField(default='Unknown Genre', help_text='Genre', max_length=255),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='key',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='rms_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='audiofile',
            name='title2',
            field=models.CharField(default='Unknown Title', help_text='Song Title', max_length=255),
        ),
        migrations.AlterField(
            model_name='audiofile',
            name='bpm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
