# Generated by Django 3.2.25 on 2025-01-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20250102_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='bpm2',
            field=models.CharField(default='Unknown BPM', help_text='Song BPM', max_length=255),
        ),
    ]
