# Generated by Django 3.2.25 on 2025-01-04 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_audiofile_bpm2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiofile',
            name='album2',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='analyzed',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='artist2',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='bpm',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='bpm2',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='genre2',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='key',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='rms_data',
        ),
        migrations.RemoveField(
            model_name='audiofile',
            name='title2',
        ),
    ]
