# Generated by Django 3.2.25 on 2025-01-17 04:01

from django.db import migrations, models
import django.db.models.deletion
import music.models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20250103_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('video_type', models.CharField(choices=[('youtube', 'YouTube'), ('uploaded', 'Uploaded')], max_length=10)),
                ('youtube_url', models.URLField(blank=True, null=True)),
                ('video_file', models.FileField(blank=True, help_text='TrackName.mp4', max_length=180, null=True, upload_to=music.models.upload_to_artist_folder3)),
                ('published_date', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(help_text='Group', null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.group')),
            ],
        ),
    ]
