# Generated by Django 3.2.25 on 2025-02-17 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Company name', max_length=100)),
                ('company_url', models.CharField(blank=True, help_text='Web page', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='clientlogo.jpg', max_length=60, null=True, upload_to='uploads/clientlogo/%Y/%m/%d/')),
                ('first_name', models.CharField(help_text='Payment contact first name', max_length=100)),
                ('last_name', models.CharField(blank=True, help_text='Payment contact last name', max_length=100)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact@email.com', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=17)),
                ('billing_top_address', models.CharField(blank=True, help_text='Attn: John Doe', max_length=100)),
                ('billing_address', models.CharField(blank=True, help_text='Street addess', max_length=100)),
                ('billing_address_city', models.CharField(blank=True, help_text='City', max_length=100)),
                ('billing_address_state', models.CharField(blank=True, help_text='State', max_length=100)),
                ('billing_address_zipcode', models.CharField(blank=True, help_text='Zip code', max_length=100)),
                ('summary', models.TextField(blank=True, help_text='Enter a brief description of the Building or Orginization', max_length=1000)),
                ('date_of_contact', models.DateField(help_text='Date of contact 5/22/2018 or 2018-05-22', null=True)),
                ('date_of_contract', models.DateField(blank=True, help_text='Date of contract 5/22/2018 or 2018-05-22', null=True)),
                ('ytd_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='year to date revenue', max_digits=18, null=True)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='total revenue', max_digits=18, null=True)),
            ],
            options={
                'verbose_name_plural': 'Client Info',
                'ordering': ['company_name'],
            },
        ),
    ]
