# Generated by Django 3.2.25 on 2025-02-17 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='Date')),
                ('site_time', models.TimeField(help_text='Start time', null=True)),
                ('site_end_time', models.TimeField(blank=True, help_text='Stop time', null=True)),
                ('site_time_after', models.TimeField(blank=True, help_text='Start time after lunch', null=True)),
                ('site_end_time_after', models.TimeField(help_text='Stop time after lunch', null=True)),
                ('artist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timecard', related_query_name='timecard', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(help_text='Project', null=True, on_delete=django.db.models.deletion.SET_NULL, to='project.project')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
