# Generated by Django 3.2.25 on 2025-02-17 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='Name of Job Site', max_length=200)),
                ('job_summary', models.TextField(help_text='Enter a brief description of the Building or Orginization', max_length=800)),
                ('profile_pic', models.ImageField(blank=True, help_text='profilepic.jpg', max_length=60, null=True, upload_to='uploads/jobsite/profile_pics/%Y/%m/%d/')),
                ('google_maps_link', models.CharField(blank=True, help_text='Google maps > click share > copy link > paste it here. https://goo.gl/maps/mqgVC9Ed4ik', max_length=200, null=True)),
                ('latlng', models.CharField(blank=True, help_text='Google maps > right click > where is > copy from right to left', max_length=200, null=True)),
                ('signed_contract', models.DateField(blank=True, help_text='Signed contract 5/22/2018 or 2018-05-22', null=True)),
                ('top_address', models.CharField(blank=True, default='Attn: Mr Rogers', help_text='Line 1 address', max_length=100)),
                ('street_address', models.CharField(blank=True, default='1234 N Strong. Dr', help_text='Line 2 Street address', max_length=100)),
                ('city', models.CharField(blank=True, help_text='City', max_length=100)),
                ('state', models.CharField(blank=True, help_text='State', max_length=100)),
                ('zipcode', models.CharField(blank=True, help_text='Zip code', max_length=100)),
                ('job_client', models.ForeignKey(help_text='Client', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobsites', related_query_name='jobsite', to='client.client')),
            ],
            options={
                'ordering': ['job_title'],
            },
        ),
    ]
