# Generated by Django 3.2.25 on 2025-02-20 09:13

from django.db import migrations, models
import django.db.models.deletion
import group.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='Genre - "Hip-Hop"', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(help_text='Group name', max_length=100)),
                ('group_url', models.CharField(blank=True, help_text='Web page', max_length=100)),
                ('logo', models.ImageField(blank=True, help_text='Logopic.jpg', max_length=60, null=True, upload_to=group.models.upload_to_group_folder)),
                ('button', models.FileField(blank=True, help_text='button.png', max_length=60, null=True, upload_to=group.models.upload_to_group_folder)),
                ('first_name', models.CharField(help_text='Payment contact first name', max_length=100)),
                ('last_name', models.CharField(blank=True, help_text='Payment contact last name', max_length=100)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact@email.com', max_length=254)),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=17)),
                ('billing_top_address', models.CharField(blank=True, help_text='Attn: John Doe', max_length=100)),
                ('billing_address', models.CharField(blank=True, help_text='Street addess', max_length=100)),
                ('billing_address_city', models.CharField(blank=True, help_text='City', max_length=100)),
                ('billing_address_state', models.CharField(blank=True, help_text='State', max_length=100)),
                ('billing_address_zipcode', models.CharField(blank=True, help_text='Zip code', max_length=100)),
                ('summary', models.TextField(blank=True, help_text='Enter a brief description of the Building or Orginization', max_length=1000)),
                ('date_of_contact', models.DateField(help_text='Date of contact 5/22/2018 or 2018-05-22', null=True)),
                ('date_of_contract', models.DateField(blank=True, help_text='Date of contract 5/22/2018 or 2018-05-22', null=True)),
                ('ytd_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='year to date revenue', max_digits=18, null=True)),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, help_text='total revenue', max_digits=18, null=True)),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram page URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter handle URL')),
            ],
            options={
                'verbose_name_plural': 'Group Info',
                'ordering': ['group_name'],
            },
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('release_date', models.DateField()),
                ('cover_art', models.ImageField(blank=True, null=True, upload_to=group.models.upload_to_group_folder_ac)),
                ('description', models.TextField(blank=True, null=True)),
                ('record_label', models.CharField(blank=True, max_length=100, null=True)),
                ('total_tracks', models.PositiveIntegerField()),
                ('duration', models.DurationField(help_text='Duration in HH:MM:SS')),
                ('spotify_link', models.URLField(blank=True, null=True)),
                ('apple_music_link', models.URLField(blank=True, null=True)),
                ('genre', models.ManyToManyField(related_name='albums', to='group.Genre')),
                ('group', models.ForeignKey(help_text='Group', null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.group')),
            ],
        ),
    ]
