# Generated by Django 3.2.25 on 2024-12-15 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('promotion_message', models.CharField(default='Subscribe to Premium for ad-free music!', max_length=255)),
                ('active_trend', models.CharField(default="Top track: 'Blinding Lights' by The Weeknd", max_length=255)),
            ],
        ),
    ]
