# Generated by Django 3.2.25 on 2024-12-15 21:15

from django.db import migrations, models
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='digital_content',
            field=models.FileField(blank=True, null=True, upload_to=shop.models.upload_to_product_folder),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.upload_to_product_folder),
        ),
    ]
