# Generated by Django 3.2.25 on 2024-12-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('category', models.CharField(choices=[('M', 'Masculine'), ('F', 'Feminine'), ('C', 'Child')], default='M', max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='sizes',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.Size'),
        ),
    ]
