# Generated by Django 3.2.25 on 2024-12-23 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_cartitem_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='category',
            field=models.CharField(blank=True, choices=[('M', 'Masculine'), ('F', 'Feminine'), ('C', 'Child')], default='M', max_length=1, null=True),
        ),
    ]
