# Generated by Django 3.2.25 on 2024-12-23 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='shipping_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
