# Generated by Django 3.2.25 on 2025-01-04 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
