# Generated by Django 3.2.25 on 2025-01-04 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_productimage_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_noshipping',
            field=models.BooleanField(default=False),
        ),
    ]
