# Generated by Django 3.2.25 on 2025-01-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_auto_20250109_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='inventory',
        ),
        migrations.AddField(
            model_name='productsize',
            name='quantity_purchased',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='quantity_purchased',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='remaining_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
