# Generated by Django 3.2.25 on 2025-01-12 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_auto_20250111_2203'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
