# Generated by Django 3.2.25 on 2025-01-12 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_delete_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='inventory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productsize'),
        ),
    ]
