# Generated by Django 3.2.25 on 2025-01-12 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_sale_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('shipping', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase_total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('purchase_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PurchasedFrom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_info', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusinessPurchaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('business_purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.businesspurchase')),
                ('product_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productsize')),
            ],
        ),
        migrations.AddField(
            model_name='businesspurchase',
            name='product_sizes',
            field=models.ManyToManyField(related_name='business_purchases', through='shop.BusinessPurchaseItem', to='shop.ProductSize'),
        ),
        migrations.AddField(
            model_name='businesspurchase',
            name='purchased_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='shop.purchasedfrom'),
        ),
    ]
