# Generated by Django 3.2.25 on 2025-01-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0030_auto_20250111_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspurchaseitem',
            name='cost',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
