# Generated by Django 3.2.25 on 2025-01-12 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0031_businesspurchaseitem_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesspurchaseitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
