# Generated by Django 3.2.25 on 2025-01-12 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_productsize_total_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='total_cost',
        ),
    ]
