# Generated by Django 3.2.25 on 2025-01-13 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_alter_businesspurchaseitem_total_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='businesspurchaseitem',
            name='total_make',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
