# Generated by Django 3.2.25 on 2025-02-17 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('material', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LicenseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_link', models.CharField(blank=True, help_text='web link https://embed.widencdn.net/img/crestron/46o04kr8yb/exact/photo_cp3_comp.jpeg', max_length=200, null=True)),
                ('install_link', models.CharField(blank=True, help_text='web link https://embed.crestron.net/mg_rg_3-series_control_systems.pdf', max_length=200, null=True)),
                ('overview', models.TextField(blank=True, help_text='Enter an overview', max_length=1000)),
                ('specifications', models.TextField(blank=True, help_text='Enter specifications', max_length=1000)),
                ('dist_part_num', models.CharField(blank=True, help_text='Enter the distributors part number.', max_length=60)),
                ('manu_part_num', models.CharField(blank=True, help_text='Enter the manufacturers part number.', max_length=60)),
                ('general_disc', models.CharField(help_text='Enter a general description.', max_length=200)),
                ('part_disc', models.CharField(blank=True, help_text='Enter manufacture name.', max_length=200)),
                ('cost', models.DecimalField(decimal_places=2, default='0.65', help_text='Cost', max_digits=18)),
                ('msrp', models.DecimalField(decimal_places=2, default='1.00', help_text='MSRP', max_digits=18)),
                ('lastmodification', models.DateTimeField(auto_now=True, help_text='Last modified', null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='devicemanufacturer',
            name='dateofcreation',
        ),
        migrations.RemoveField(
            model_name='devicematerial',
            name='dateofcreation',
        ),
        migrations.RemoveField(
            model_name='devicematerial',
            name='part_num',
        ),
        migrations.RemoveField(
            model_name='distributor',
            name='dateofcreation',
        ),
        migrations.RemoveField(
            model_name='hardwarematerial',
            name='dateofcreation',
        ),
        migrations.RemoveField(
            model_name='hardwarematerial',
            name='part_num',
        ),
        migrations.RemoveField(
            model_name='softwarematerial',
            name='dateofcreation',
        ),
        migrations.RemoveField(
            model_name='softwarematerial',
            name='part_num',
        ),
        migrations.RemoveField(
            model_name='wirematerial',
            name='dateofcreation',
        ),
        migrations.RemoveField(
            model_name='wirematerial',
            name='part_num',
        ),
        migrations.AddField(
            model_name='devicemanufacturer',
            name='company_url',
            field=models.CharField(blank=True, help_text='Web page', max_length=100),
        ),
        migrations.AddField(
            model_name='devicemanufacturer',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='devicemanufacturer',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=17),
        ),
        migrations.AddField(
            model_name='devicemanufacturer',
            name='contract_info',
            field=models.TextField(blank=True, help_text='Contract Information', max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='devicemanufacturer',
            name='dateofcontract',
            field=models.DateTimeField(blank=True, help_text='Contract start date', null=True),
        ),
        migrations.AddField(
            model_name='devicemanufacturer',
            name='distributor',
            field=models.ManyToManyField(blank=True, help_text='Select possable distributors', related_name='Distributor', to='material.Distributor'),
        ),
        migrations.AddField(
            model_name='devicemanufacturer',
            name='first_name',
            field=models.CharField(blank=True, help_text='Contact first name', max_length=100),
        ),
        migrations.AddField(
            model_name='devicemanufacturer',
            name='last_name',
            field=models.CharField(blank=True, help_text='Contact last name', max_length=100),
        ),
        migrations.AddField(
            model_name='devicemanufacturer',
            name='logo',
            field=models.ImageField(blank=True, help_text='devicelogopic.jpg', max_length=60, null=True, upload_to='uploads/distributor/logo_pics/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='devicemanufacturer',
            name='manu_top_address',
            field=models.CharField(blank=True, help_text='Attn: John Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='devicemanufacturer',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a brief description of the Building or Orginization', max_length=1000),
        ),
        migrations.AddField(
            model_name='devicematerial',
            name='dist_part_num',
            field=models.CharField(blank=True, help_text='Enter the distributors part number.', max_length=60),
        ),
        migrations.AddField(
            model_name='devicematerial',
            name='install_link',
            field=models.CharField(blank=True, help_text='web link https://embed.crestron.net/mg_rg_3-series_control_systems.pdf', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='devicematerial',
            name='manu_part_num',
            field=models.CharField(blank=True, help_text='Enter the manufacturers part number.', max_length=60),
        ),
        migrations.AddField(
            model_name='devicematerial',
            name='overview',
            field=models.TextField(blank=True, help_text='Enter an overview', max_length=1000),
        ),
        migrations.AddField(
            model_name='devicematerial',
            name='pic_link',
            field=models.CharField(blank=True, help_text='web link https://embed.widencdn.net/img/crestron/46o04kr8yb/exact/photo_cp3_comp.jpeg', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='devicematerial',
            name='specifications',
            field=models.TextField(blank=True, help_text='Enter specifications', max_length=1000),
        ),
        migrations.AddField(
            model_name='distributor',
            name='billing_top_address',
            field=models.CharField(blank=True, help_text='Attn: John Doe', max_length=100),
        ),
        migrations.AddField(
            model_name='distributor',
            name='company_url',
            field=models.CharField(blank=True, help_text='Web page', max_length=100),
        ),
        migrations.AddField(
            model_name='distributor',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Contact@email.com', max_length=254),
        ),
        migrations.AddField(
            model_name='distributor',
            name='contact_phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=17),
        ),
        migrations.AddField(
            model_name='distributor',
            name='contract_info',
            field=models.TextField(blank=True, help_text='Contract Information', max_length=4000, null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='dateofcontract',
            field=models.DateTimeField(blank=True, help_text='Contract start date', null=True),
        ),
        migrations.AddField(
            model_name='distributor',
            name='first_name',
            field=models.CharField(blank=True, help_text='Contact first name', max_length=100),
        ),
        migrations.AddField(
            model_name='distributor',
            name='last_name',
            field=models.CharField(blank=True, help_text='Contact last name', max_length=100),
        ),
        migrations.AddField(
            model_name='distributor',
            name='logo',
            field=models.ImageField(blank=True, help_text='distlogopic.jpg', max_length=60, null=True, upload_to='uploads/distributor/logo_pics/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='distributor',
            name='summary',
            field=models.TextField(blank=True, help_text='Enter a brief description of the Building or Orginization', max_length=1000),
        ),
        migrations.AddField(
            model_name='hardwarematerial',
            name='cost',
            field=models.DecimalField(decimal_places=2, default='0.60', help_text='Cost', max_digits=18),
        ),
        migrations.AddField(
            model_name='hardwarematerial',
            name='dist_part_num',
            field=models.CharField(blank=True, help_text='Enter the distributors part number.', max_length=60),
        ),
        migrations.AddField(
            model_name='hardwarematerial',
            name='install_link',
            field=models.CharField(blank=True, help_text='web link https://embed.crestron.net/mg_rg_3-series_control_systems.pdf', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hardwarematerial',
            name='manu_part_num',
            field=models.CharField(blank=True, help_text='Enter the manufacturers part number.', max_length=60),
        ),
        migrations.AddField(
            model_name='hardwarematerial',
            name='msrp',
            field=models.DecimalField(decimal_places=2, default='1.00', help_text='MSRP', max_digits=18),
        ),
        migrations.AddField(
            model_name='hardwarematerial',
            name='overview',
            field=models.TextField(blank=True, help_text='Enter an overview', max_length=1000),
        ),
        migrations.AddField(
            model_name='hardwarematerial',
            name='part_disc',
            field=models.CharField(blank=True, help_text='Enter manufacture name.', max_length=200),
        ),
        migrations.AddField(
            model_name='hardwarematerial',
            name='pic_link',
            field=models.CharField(blank=True, help_text='web link https://embed.widencdn.net/img/crestron/46o04kr8yb/exact/photo_cp3_comp.jpeg', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='hardwarematerial',
            name='specifications',
            field=models.TextField(blank=True, help_text='Enter specifications', max_length=1000),
        ),
        migrations.AddField(
            model_name='softwarematerial',
            name='dist_part_num',
            field=models.CharField(blank=True, help_text='Enter the distributors part number.', max_length=60),
        ),
        migrations.AddField(
            model_name='softwarematerial',
            name='install_link',
            field=models.CharField(blank=True, help_text='web link https://embed.crestron.net/mg_rg_3-series_control_systems.pdf', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='softwarematerial',
            name='manu_part_num',
            field=models.CharField(blank=True, help_text='Enter the manufacturers part number.', max_length=60),
        ),
        migrations.AddField(
            model_name='softwarematerial',
            name='overview',
            field=models.TextField(blank=True, help_text='Enter an overview', max_length=1000),
        ),
        migrations.AddField(
            model_name='softwarematerial',
            name='pic_link',
            field=models.CharField(blank=True, help_text='web link https://embed.widencdn.net/img/crestron/46o04kr8yb/exact/photo_cp3_comp.jpeg', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='softwarematerial',
            name='specifications',
            field=models.TextField(blank=True, help_text='Enter specifications', max_length=1000),
        ),
        migrations.AddField(
            model_name='wirematerial',
            name='dist_part_num',
            field=models.CharField(blank=True, help_text='Enter the distributors part number.', max_length=60),
        ),
        migrations.AddField(
            model_name='wirematerial',
            name='install_link',
            field=models.CharField(blank=True, help_text='web link https://embed.crestron.net/mg_rg_3-series_control_systems.pdf', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wirematerial',
            name='manu_part_num',
            field=models.CharField(blank=True, help_text='Enter the manufacturers part number.', max_length=60),
        ),
        migrations.AddField(
            model_name='wirematerial',
            name='overview',
            field=models.TextField(blank=True, help_text='Enter an overview', max_length=1000),
        ),
        migrations.AddField(
            model_name='wirematerial',
            name='pic_link',
            field=models.CharField(blank=True, help_text='web link https://embed.widencdn.net/img/crestron/46o04kr8yb/exact/photo_cp3_comp.jpeg', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='wirematerial',
            name='specifications',
            field=models.TextField(blank=True, help_text='Enter specifications', max_length=1000),
        ),
        migrations.AlterField(
            model_name='devicemanufacturer',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='devicematerial',
            name='dist',
        ),
        migrations.AddField(
            model_name='devicematerial',
            name='dist',
            field=models.ManyToManyField(blank=True, help_text='distributor', related_name='ddistributor', related_query_name='ddistributor', to='material.Distributor'),
        ),
        migrations.AlterField(
            model_name='devicematerial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='devicematerial',
            name='part_disc',
            field=models.CharField(blank=True, help_text='Enter manufacture name.', max_length=200),
        ),
        migrations.AlterField(
            model_name='distributor',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='hardwarematerial',
            name='dist',
        ),
        migrations.AddField(
            model_name='hardwarematerial',
            name='dist',
            field=models.ManyToManyField(blank=True, help_text='hdistributor', related_name='hdistributor', related_query_name='hdistributor', to='material.Distributor'),
        ),
        migrations.AlterField(
            model_name='hardwarematerial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.RemoveField(
            model_name='softwarematerial',
            name='dist',
        ),
        migrations.AddField(
            model_name='softwarematerial',
            name='dist',
            field=models.ManyToManyField(blank=True, help_text='sdistributor', related_name='sdistributor', related_query_name='sdistributor', to='material.Distributor'),
        ),
        migrations.AlterField(
            model_name='softwarematerial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='softwarematerial',
            name='part_disc',
            field=models.CharField(blank=True, help_text='Enter manufacture name.', max_length=200),
        ),
        migrations.AlterField(
            model_name='softwarematerial',
            name='smfg',
            field=models.ForeignKey(help_text='sManufacturer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='smanufacturer', related_query_name='smanufacturer', to='material.devicemanufacturer'),
        ),
        migrations.RemoveField(
            model_name='wirematerial',
            name='dist',
        ),
        migrations.AddField(
            model_name='wirematerial',
            name='dist',
            field=models.ManyToManyField(blank=True, help_text='wdistributor', related_name='wdistributor', related_query_name='wdistributor', to='material.Distributor'),
        ),
        migrations.AlterField(
            model_name='wirematerial',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='wirematerial',
            name='part_disc',
            field=models.CharField(blank=True, help_text='Enter manufacture name.', max_length=200),
        ),
        migrations.AlterField(
            model_name='wirematerial',
            name='wmfg',
            field=models.ForeignKey(help_text='wManufacturer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wmanufacturer', related_query_name='wmanufacturer', to='material.devicemanufacturer'),
        ),
        migrations.DeleteModel(
            name='SoftwareManufacturer',
        ),
        migrations.DeleteModel(
            name='WireManufacturer',
        ),
        migrations.AddField(
            model_name='licensematerial',
            name='dist',
            field=models.ManyToManyField(blank=True, help_text='distributor', related_name='ldistributor', related_query_name='ldistributor', to='material.Distributor'),
        ),
        migrations.AddField(
            model_name='licensematerial',
            name='dmfg',
            field=models.ForeignKey(help_text='dManufacturer', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lmanufacturer', related_query_name='lmanufacturer', to='material.devicemanufacturer'),
        ),
    ]
