# Generated by Django 3.2.25 on 2025-02-17 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onsite_date', models.DateField(blank=True, help_text='onsite date', null=True)),
                ('installed_date', models.DateField(blank=True, help_text='installed date', null=True)),
                ('qty', models.PositiveIntegerField(default='1', help_text='Quantity', null=True)),
                ('cost', models.DecimalField(decimal_places=2, default='1.00', help_text='Cost', max_digits=18)),
                ('device_status', models.CharField(blank=True, choices=[('q', 'Quoted'), ('p', 'Purchased'), ('o', 'Onsite'), ('i', 'Installed')], default='q', help_text='Device Status', max_length=1)),
                ('purchased_date', models.DateField(blank=True, help_text='purchased date', null=True)),
                ('dateofcreation', models.DateTimeField(auto_now_add=True, help_text='Created at', null=True)),
                ('lastmodification', models.DateTimeField(auto_now=True, help_text='Last modified', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onsite_date', models.DateField(blank=True, help_text='onsite date', null=True)),
                ('installed_date', models.DateField(blank=True, help_text='installed date', null=True)),
                ('qty', models.PositiveIntegerField(blank=True, help_text='Quantity', null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost', max_digits=18, null=True)),
                ('hardware_status', models.CharField(blank=True, choices=[('q', 'Quoted'), ('p', 'Purchased'), ('o', 'Onsite'), ('i', 'Installed')], default='q', help_text='Wire Status', max_length=1)),
                ('purchased_date', models.DateField(blank=True, help_text='purchased date', null=True)),
                ('dateofcreation', models.DateTimeField(auto_now_add=True, help_text='Created at', null=True)),
                ('lastmodification', models.DateTimeField(auto_now=True, help_text='Last modified', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onsite_date', models.DateField(blank=True, help_text='onsite date', null=True)),
                ('installed_date', models.DateField(blank=True, help_text='installed date', null=True)),
                ('qty', models.PositiveIntegerField(default='1', help_text='Quantity', null=True)),
                ('cost', models.DecimalField(decimal_places=2, default='1.00', help_text='Cost', max_digits=18)),
                ('license_status', models.CharField(blank=True, choices=[('q', 'Quoted'), ('p', 'Purchased'), ('o', 'Onsite'), ('i', 'Installed')], default='q', help_text='license Status', max_length=1)),
                ('purchased_date', models.DateField(blank=True, help_text='purchased date', null=True)),
                ('dateofcreation', models.DateTimeField(auto_now_add=True, help_text='Created at', null=True)),
                ('lastmodification', models.DateTimeField(auto_now=True, help_text='Last modified', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_num', models.BigIntegerField(help_text='Job number')),
                ('revision', models.CharField(blank=True, help_text='Revision', max_length=200, null=True)),
                ('job_name', models.CharField(default='Job Name', help_text='Name of job', max_length=200)),
                ('install_overview', models.TextField(blank=True, help_text='Enter the overview of the install', max_length=8000, null=True)),
                ('pricing_disclaim', models.TextField(blank=True, help_text='Enter the price disclaimer of the install', max_length=8000, null=True)),
                ('site_contact', models.TextField(blank=True, help_text='Who is the site contact for the install', max_length=200, null=True)),
                ('date_requested', models.DateField(blank=True, help_text='Start Date', null=True)),
                ('due_date', models.DateField(blank=True, help_text='Due Date', null=True)),
                ('finished_date', models.DateField(blank=True, help_text='Date of completion', null=True)),
                ('profile_pic', models.ImageField(blank=True, help_text='profilepic.jpg', max_length=60, null=True, upload_to='uploads/project/profile_pics/%Y/%m/%d/')),
                ('burden', models.DecimalField(blank=True, decimal_places=2, default='1.65', help_text='Burden Percentage', max_digits=5, null=True)),
                ('markup', models.DecimalField(blank=True, decimal_places=2, default='1.15', help_text='Material Markup', max_digits=5, null=True)),
                ('licmarkup', models.DecimalField(blank=True, decimal_places=2, default='1.15', help_text='Sofware and License Markup', max_digits=5, null=True)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, default='4000.', help_text='Estimated Cost', max_digits=20, null=True)),
                ('contract_value', models.DecimalField(blank=True, decimal_places=2, default='4500.', help_text='Contract Value', max_digits=20, null=True)),
                ('paid_date', models.DateField(blank=True, help_text='Date paid', null=True)),
                ('lastmodification', models.DateTimeField(auto_now=True, help_text='Last modified', null=True)),
                ('job_status', models.CharField(blank=True, choices=[('p', 'Prospect'), ('q', 'Quoted'), ('o', 'Installing'), ('c', 'Complete'), ('s', 'Service'), ('t', 'T & M'), ('i', 'Invoiced'), ('m', 'Paid'), ('l', 'Lost/Cancelled')], default='p', help_text='Install Status', max_length=1)),
                ('tax_status', models.CharField(blank=True, choices=[('p', 'P.Y. Tribal Tax'), ('o', 'T.O. Tribal Tax'), ('x', 'Tax exempt'), ('t', 'Taxable'), ('s', 'Sub contractor')], default='s', help_text='Tax Status', max_length=1)),
                ('division_status', models.CharField(blank=True, choices=[('c', 'Communications'), ('s', 'Special Systems')], help_text='Division Status', max_length=1)),
                ('type_status', models.CharField(blank=True, choices=[('c', 'Commercial'), ('r', 'Residential')], default='c', help_text='Type Status', max_length=1)),
            ],
            options={
                'ordering': ['-job_num'],
            },
        ),
        migrations.CreateModel(
            name='ScopeOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(help_text='Area in building', max_length=200)),
                ('system_type', models.CharField(default='Cabling / AV / CCTV / Access Control', help_text='System Type', max_length=200)),
                ('priority', models.PositiveIntegerField(default='9999', help_text='Priorty')),
                ('dateofcreation', models.DateTimeField(auto_now_add=True, help_text='Created at', null=True)),
                ('lastmodification', models.DateTimeField(auto_now=True, help_text='Last modified', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Software',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onsite_date', models.DateField(blank=True, help_text='onsite date', null=True)),
                ('installed_date', models.DateField(blank=True, help_text='installed date', null=True)),
                ('qty', models.PositiveIntegerField(blank=True, help_text='Quantity', null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, help_text='Cost', max_digits=18, null=True)),
                ('software_status', models.CharField(blank=True, choices=[('q', 'Quoted'), ('p', 'Purchased'), ('o', 'Onsite'), ('i', 'Installed')], default='q', help_text='Software Status', max_length=1)),
                ('purchased_date', models.DateField(blank=True, help_text='purchased date', null=True)),
                ('dateofcreation', models.DateTimeField(auto_now_add=True, help_text='Created at', null=True)),
                ('lastmodification', models.DateTimeField(auto_now=True, help_text='Last modified', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_name', models.CharField(blank=True, help_text='Travel Name', max_length=200, null=True)),
                ('hotel_name', models.CharField(blank=True, help_text='Hotel/Motel Name', max_length=200, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default='0.00', help_text='Cost', max_digits=18)),
                ('gas_estimate', models.DecimalField(decimal_places=2, default='60.00', help_text='Cost', max_digits=18)),
                ('hotel_status', models.CharField(blank=True, choices=[('q', 'Quoted'), ('p', 'Purchased')], default='q', help_text='travel Status', max_length=1)),
                ('purchased_date', models.DateField(blank=True, help_text='purchased date', null=True)),
                ('dateofcreation', models.DateTimeField(auto_now_add=True, help_text='Created at', null=True)),
                ('lastmodification', models.DateTimeField(auto_now=True, help_text='Last modified', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onsite_date', models.DateField(blank=True, help_text='onsite date', null=True)),
                ('installed_date', models.DateField(blank=True, help_text='installed date', null=True)),
                ('length', models.PositiveIntegerField(default='1000', help_text='Length', null=True)),
                ('cost_per_foot', models.DecimalField(decimal_places=2, default='1.20', help_text='Per foot', max_digits=18)),
                ('wire_status', models.CharField(blank=True, choices=[('q', 'Quoted'), ('p', 'Purchased'), ('o', 'Onsite'), ('i', 'Installed')], default='q', help_text='Wire Status', max_length=1)),
                ('purchased_date', models.DateField(blank=True, help_text='purchased date', null=True)),
                ('dateofcreation', models.DateTimeField(auto_now_add=True, help_text='Created at', null=True)),
                ('lastmodification', models.DateTimeField(auto_now=True, help_text='Last modified', null=True)),
                ('project', models.ForeignKey(blank=True, help_text='Project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='WirProj', to='project.project')),
            ],
        ),
    ]
