# Generated by Django 3.2.25 on 2025-02-17 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('jobsite', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0001_initial'),
        ('material', '0002_auto_20250216_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='wire',
            name='task',
            field=models.ForeignKey(blank=True, help_text='task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wtaskattached', related_query_name='wtaskattached', to='todo.task'),
        ),
        migrations.AddField(
            model_name='wire',
            name='wire',
            field=models.ForeignKey(blank=True, help_text='wMaterial', null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.wirematerial'),
        ),
        migrations.AddField(
            model_name='travel',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='TravelProj', to='project.project'),
        ),
        migrations.AddField(
            model_name='travel',
            name='task',
            field=models.ForeignKey(blank=True, help_text='task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Traveltaskattached', related_query_name='traveltaskattached', to='todo.task'),
        ),
        migrations.AddField(
            model_name='software',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SofProj', to='project.project'),
        ),
        migrations.AddField(
            model_name='software',
            name='software',
            field=models.ForeignKey(help_text='Software', null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.softwarematerial'),
        ),
        migrations.AddField(
            model_name='software',
            name='task',
            field=models.ForeignKey(help_text='task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staskattached', related_query_name='staskattached', to='todo.task'),
        ),
        migrations.AddField(
            model_name='scopeofwork',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ScopesProj', to='project.project'),
        ),
        migrations.AddField(
            model_name='project',
            name='artist',
            field=models.ManyToManyField(blank=True, help_text='Select artist for this install', related_name='Artist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='estimator',
            field=models.ForeignKey(blank=True, help_text='Estimator', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Estimator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='foremen',
            field=models.ForeignKey(blank=True, help_text='Foremen', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Foremen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='jobsite',
            field=models.ForeignKey(help_text='Job site', null=True, on_delete=django.db.models.deletion.SET_NULL, to='jobsite.jobsite'),
        ),
        migrations.AddField(
            model_name='project',
            name='lead',
            field=models.ManyToManyField(blank=True, help_text='Select leads for this install', related_name='Lead', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='projectmanager',
            field=models.ForeignKey(blank=True, help_text='Project Manager', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ProjectManager', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='license',
            name='license',
            field=models.ForeignKey(blank=True, help_text='wlicense', null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.licensematerial'),
        ),
        migrations.AddField(
            model_name='license',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='LicProj', to='project.project'),
        ),
        migrations.AddField(
            model_name='license',
            name='task',
            field=models.ForeignKey(blank=True, help_text='task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lictaskattached', related_query_name='lictaskattached', to='todo.task'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='hardware',
            field=models.ForeignKey(help_text='hardware', null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.hardwarematerial'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='HarProj', to='project.project'),
        ),
        migrations.AddField(
            model_name='hardware',
            name='task',
            field=models.ForeignKey(help_text='task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='htaskattached', related_query_name='htaskattached', to='todo.task'),
        ),
        migrations.AddField(
            model_name='device',
            name='device',
            field=models.ForeignKey(blank=True, help_text='wDevice', null=True, on_delete=django.db.models.deletion.SET_NULL, to='material.devicematerial'),
        ),
        migrations.AddField(
            model_name='device',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Project', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='DevProj', to='project.project'),
        ),
        migrations.AddField(
            model_name='device',
            name='task',
            field=models.ForeignKey(blank=True, help_text='task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taskattached', related_query_name='taskattached', to='todo.task'),
        ),
    ]
