# Generated by Django 3.2.25 on 2025-02-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munkz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='has_calendar_access',
            field=models.BooleanField(default=False, help_text='Can the artist access the calendar?'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='has_task_management',
            field=models.BooleanField(default=False, help_text='Can the artist manage tasks?'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
