# Generated by Django 3.2.25 on 2025-02-19 04:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
        ('munkz', '0002_auto_20250213_2130'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='calendar',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedule.calendar'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='events',
            field=models.ManyToManyField(blank=True, related_name='artist_events', to='schedule.Event'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='show_public_events',
            field=models.BooleanField(default=True, help_text='Show events on public profile'),
        ),
    ]
