# Generated by Django 3.2.25 on 2025-02-20 09:13

from django.db import migrations, models
import munkz.models


class Migration(migrations.Migration):

    dependencies = [
        ('munkz', '0003_auto_20250218_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='resume',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='stage_name',
            field=models.CharField(blank=True, help_text='Artist or stage name', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='cover_photo',
            field=models.ImageField(blank=True, help_text='Cover photo', null=True, upload_to=munkz.models.upload_to_cover_photos),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='profile_pic',
            field=models.ImageField(blank=True, help_text='Profile picture', null=True, upload_to=munkz.models.upload_to_profile_folder),
        ),
    ]
